(CONFIDENTIAL) INTERNAL USE ONLY, NOT FOR EXTERNAL DISTRIBUTION

<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>

In [1]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>

# Bias and Varience

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
# the physical law says: S = 1/2 * F / M * t*2
# S: displacement, M: mass, F: force
# Let's say we know nothing about physics
# Given this data measure points: 
# (t, S) for N points, we want to predict for (t_new) what is S_new

In [ ]:
ground_truth_coef = 1./2 * 10 / 2
t = np.random.random(10) * 3
ground_truth_result = ground_truth_coef * t**2

# measure error
measure_result = ground_truth_result + np.random.randn(10)*2

t_new = np.random.random(5) * 3

In [ ]:
from sklearn import linear_model, metrics
lm_lr = linear_model.LinearRegression()

In [ ]:
# Under fitting, what is the error? (using 1 order)
# we need to run it over multple times to see the difference
N = 10000
error = []
error_train = []
for i in range(N):
    t = np.random.random(10) * 3
    ground_truth_result = ground_truth_coef * t**2
    measure_result = ground_truth_result + np.random.randn(10)*2
    t.resize([len(t), 1])
    
    lm_lr.fit(t, measure_result)
    
    t_new = (np.random.random(5) * 3).reshape(-1, 1)
    t_truth = ground_truth_coef * t_new[:,0]**2
    t_pred = lm_lr.predict(t_new)
    
    error.append(metrics.mean_squared_error(t_pred, t_truth))
    #error_train.append(metrics.mean_squared_error(t, measure_result))
    
error = np.array(error)
#error_train = np.array(error_train)

In [ ]:
#print error_train.mean(), error_train.std()
print error.mean(), error.std()

In [ ]:
# Over fitting, what is the error? (using 3 order)
N = 10000
error = []
for i in range(N):
    t = (np.random.random(10) * 3).reshape([-1, 1])
    ground_truth_result = ground_truth_coef * t**2
    measure_result = ground_truth_result + (np.random.randn(10)*2).reshape([-1,1])
    t = np.hstack([t, t**2, t**3])
    
    lm_lr.fit(t, measure_result)
    
    t_new = (np.random.random(5)).reshape([-1, 1])
    t_new = np.hstack([t_new, t_new**2, t_new**3])
    t_truth = ground_truth_coef * t_new[:,0]**2
    t_pred = lm_lr.predict(t_new)
    
    error.append(metrics.mean_squared_error(t_pred, t_truth))
    #error_train.append(metrics.mean_squared_error(t[:,0], measure_result))

    
error = np.array(error)
#error_train = np.array(error_train)

In [ ]:
print error.mean(), error.std()

In [ ]:
# Over fitting, what is the error? (using 2 order)
N = 10000
error = []
for i in range(N):
    t = (np.random.random(10) * 3).reshape([-1, 1])
    ground_truth_result = ground_truth_coef * t**2
    measure_result = ground_truth_result + (np.random.randn(10)*2).reshape([-1,1])
    t = np.hstack([t, t**2])
    
    lm_lr.fit(t, measure_result)
    
    t_new = (np.random.random(5)).reshape([-1, 1])
    t_new = np.hstack([t_new, t_new**2])
    t_truth = ground_truth_coef * t_new[:,0]**2
    t_pred = lm_lr.predict(t_new)
    
    error.append(metrics.mean_squared_error(t_pred, t_truth))
    
error = np.array(error)

In [ ]:
print error.mean(), error.std()

In [ ]:
# Balance Varience & Bias
np.random.seed(1)
x = (np.random.random([30, 1]) * 6 - 4).ravel()
y = -2*(5*x)**3 - 30 * (5*x) **2 + 100*(10*x) + 500 * np.random.randn(len(x))
plt.scatter(x,y)
plt.show()

In [ ]:
# Q1. Under ALL circumstances, is it that the more complicated a model is, the lower training error? 
# Q2. Under ALL circumstances, is it that the more complicated a model is, the lower testing error? 
# Q3. How does standard deviation looks like for both training & testing errors

## Bias & varience: model complexity

In [ ]:
# single variable linear model (low varience)

# nearest-neighbour model (high varience) 

In [ ]:
# Q. is single linear regression model high bias, low varience? 

In [ ]:
# Data set 1. 
N = 300
np.random.seed(1)
x = (np.random.random([N, 1]) * 6 - 4).ravel()
y = -2*(5*x)**3 - 30 * (5*x) **2 + 100*(10*x) + 500 * np.random.randn(len(x))
plt.scatter(x,y)
plt.show()

In [ ]:
# Data set 2. 
N = 5000
r = np.random.rand(N)
theta = np.random.rand(N) * 1.0 * np.pi
y = np.sin(theta) * r
plt.scatter(r, theta, c=y)

## Bias & varience: data size

In [ ]:
data = datasets.make_regression(n_samples=1000, n_features=100, n_informative=100, noise=100)
X = data[0]
Y = data[1]
print X.shape, Y.shape

In [ ]:
ts_range = np.arange(0.05, 1, 0.05)
N_run = 50
t_score = []
v_score = []
for train_s in ts_range:
    t_score.append([])
    v_score.append([])
    for iseed in range(N_run):
        X1, X2, Y1, Y2 = cross_validation.train_test_split(X, Y, train_size=train_s, random_state=iseed)
        rlm = linear_model.LinearRegression()
        rlm.fit(X1, Y1)
        t_score[-1].append(metrics.r2_score(Y1, rlm.predict(X1)))
        v_score[-1].append(metrics.r2_score(Y2, rlm.predict(X2)))
    # print train_s

In [ ]:
t_score = np.array(t_score)
v_score = np.array(v_score)

In [ ]:
# errorbar plot (training and validation)
fig = plt.figure()
ax = fig.add_subplot(1,1,1)

x = range(t_score.shape[0])[2:]
y = t_score.mean(axis=1)[2:]
s = t_score.std(axis=1)[2:]
ax.errorbar(x, y, yerr=s)
fig.show()

In [ ]:
# errorbar plot (training and validation)
fig = plt.figure()
ax = fig.add_subplot(1,1,1)

x = range(t_score.shape[0])[2:]
y = t_score.mean(axis=1)[2:]
s = t_score.std(axis=1)[2:]
ax.errorbar(x, y, yerr=s)
x = range(v_score.shape[0])[2:]
y = v_score.mean(axis=1)[2:]
s = v_score.std(axis=1)[2:]
ax.errorbar(x, y, yerr=s)
fig.show()

# Regression in-depth

In [ ]:
# Regular linear regression

# Lasso

# Ridge

# Elastic-net

## Regularization

In [ ]:
# X is the 10x10 Hilbert matrix
X = 1. / (np.arange(1, 11) + np.arange(0, 10)[:, np.newaxis])
y = np.ones(10)
data = datasets.make_regression(n_samples=100, n_features=10, n_informative=10, random_state=0)

X = data[0]
y = data[1]

###############################################################################
# Compute paths

n_alphas = 200
alphas = np.logspace(-1, 5, n_alphas)
clf = linear_model.Ridge()

coefs = []
for a in alphas:
    clf.set_params(alpha=a)
    clf.fit(X, y)
    coefs.append(clf.coef_)

###############################################################################
# Display results

ax = plt.gca()
ax.set_color_cycle(['b', 'r', 'g', 'c', 'k', 'y', 'm'])

ax.plot(alphas, coefs)
ax.set_xscale('log')
ax.set_xlim(ax.get_xlim()[::-1])  # reverse axis
plt.xlabel('alpha')
plt.ylabel('weights')
plt.title('Ridge coefficients as a function of the regularization')
plt.axis('tight')
plt.show()

In [ ]:
###############################################################################
# Compute paths

n_alphas = 200
alphas = np.logspace(-1, 5, n_alphas)
clf = linear_model.Lasso()

coefs = []
for a in alphas:
    clf.set_params(alpha=a)
    clf.fit(X, y)
    coefs.append(clf.coef_)

###############################################################################
# Display results

ax = plt.gca()
ax.set_color_cycle(['b', 'r', 'g', 'c', 'k', 'y', 'm'])

ax.plot(alphas, coefs)
ax.set_xscale('log')
ax.set_xlim(ax.get_xlim()[::-1])  # reverse axis
plt.xlabel('alpha')
plt.ylabel('weights')
plt.title('Lasso coefficients as a function of the regularization')
plt.axis('tight')
plt.show()

In [ ]:
###############################################################################
# Compute paths

n_alphas = 200
alphas = np.logspace(-1, 5, n_alphas)
clf = linear_model.ElasticNet(l1_ratio=0.5)

coefs = []
for a in alphas:
    clf.set_params(alpha=a)
    clf.fit(X, y)
    coefs.append(clf.coef_)

###############################################################################
# Display results

ax = plt.gca()
ax.set_color_cycle(['b', 'r', 'g', 'c', 'k', 'y', 'm'])

ax.plot(alphas, coefs)
ax.set_xscale('log')
ax.set_xlim(ax.get_xlim()[::-1])  # reverse axis
plt.xlabel('alpha')
plt.ylabel('weights')
plt.title('ES coefficients as a function of the regularization')
plt.axis('tight')
plt.show()

In [ ]:
# Excercise, run the regression over friedman datasets, see which variables are selected at different alpha
data = datasets.make_friedman1(random_state=0)
X = data[0]
y = data[1]

## Stochastic gradient descent (SGD)

In [ ]:
# http://vis.supstat.com/2013/03/gradient-descent-algorithm-with-r/
# 

In [ ]:
data = datasets.make_regression(n_samples=10000, n_features=1000, n_informative=1000)
X = data[0]
y = data[1]

In [ ]:
# compare efficiency and accuracy for SGD and tradition LR

In [ ]:
%%time
lrg1 = linear_model.LinearRegression()
lrg1.fit(X, y)

In [ ]:
%%time
lrg2 = linear_model.SGDRegressor()
lrg2.fit(X,y)

## Preprocessing

In [2]:
from sklearn import datasets, preprocessing

In [16]:
X, Y = datasets.make_regression(n_samples=1000, n_features=2, n_informative=2)

In [17]:
X1 = X
X2 = X.copy()
X2[:,1] *= 1000

In [19]:
from sklearn import linear_model

In [20]:
m1 = linear_model.LinearRegression()
m1.fit(X1, Y)

m2 = linear_model.LinearRegression()
m2.fit(X2, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
m1.coef_

array([ 77.2136552 ,  88.18939999])

In [22]:
m2.coef_

array([ 77.2136552,   0.0881894])

In [24]:
m1 = linear_model.SGDRegressor()
m1.fit(X1, Y)

m2 = linear_model.SGDRegressor()
m2.fit(X2, Y)

SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', n_iter=5, penalty='l2', power_t=0.25,
       random_state=None, shuffle=True, verbose=0, warm_start=False)

In [27]:
m1.coef_, m1.intercept_

(array([ 77.19276286,  88.15315519]), array([ 0.01569117]))

In [29]:
from sklearn import metrics

In [30]:
metrics.mean_squared_error(m1.predict(X1), Y)

0.001999487193715426

In [28]:
m2.coef_, m2.intercept_

(array([ -1.54393637e+11,   5.94092367e+11]), array([ -1.33254479e+11]))

In [31]:
metrics.mean_squared_error(m2.predict(X2), Y)

3.5607337515545333e+29

## Robustness regression

In [ ]:
# Why robustness is needed?

x = np.random.random(100) * 10 
y = 2.0 * x + 30 + 2.0 * np.random.rand(len(x))

xn = np.random.random(10) * 3
yn = 6.0 * xn + 4 + 2.0 * np.random.rand(len(xn))

xnew = np.concatenate([x,xn])
ynew = np.concatenate([y,yn])

xnew = xnew.reshape([-1,1])

In [ ]:
# RANSAC
# https://upload.wikimedia.org/wikipedia/commons/c/c0/RANSAC_LINIE_Animiert.gif